# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diplom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='number')),
                ('is_busy', models.BooleanField(db_index=True, default=False, verbose_name='is_busy')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diplom.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField(default=0, verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Raspberry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField(default='', verbose_name='room')),
                ('domain', models.TextField(default='', verbose_name='domain')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(default='', verbose_name='time')),
                ('mode', models.BooleanField(default=False, verbose_name='mode')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diplom.Device')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diplom.DeviceType'),
        ),
        migrations.AddField(
            model_name='channel',
            name='raspberry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diplom.Raspberry'),
        ),
    ]
