# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0002_auto_20170415_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=255, verbose_name='position'),
        ),
    ]
